### ISSUE TITLE
Bug in pwmType to find PWMs

### ISSUE THREAD

**Issue by jkzebrafish** [GreenleafLab/chromVAR#23]
Hi Alicia, great project, excited to get this to work! 
Looks like the pwmType method has a small easily fixable bug.  
I have:
![version](https://user-images.githubusercontent.com/32973923/31851240-b0454b5e-b616-11e7-841d-a45c7335c2d7.JPG)
![pwmlistisok](https://user-images.githubusercontent.com/32973923/31851204-e7e4da26-b615-11e7-9d7b-13111c6950f0.JPG)
But then:
![error](https://user-images.githubusercontent.com/32973923/31851205-f1376792-b615-11e7-908f-745ea83fa986.JPG)

This seems to be line 3 of pwmType(...) method, where the all.equal(...) call lacks the "current" argument, and hence always returns an error, which causes the isTRUE(...) call to by default return FALSE.  Maybe it's something else but that seems like the first obvious thing to check.
![pwmtype_line3bug](https://user-images.githubusercontent.com/32973923/31851209-073384f4-b616-11e7-8e97-48af126e7d0a.JPG)

Thanks Alicia!  Keep up the good work.
Best,
John Mich

**Comment by AliciaSchep** [comment]
Thanks for posting!  I'll take a look and update here when bug is fixed.

**Comment by AliciaSchep** [comment]
@jkzebrafish There is a current argument, `rep(1, length(pwm)`, so that is not source of bug.  

I think it is that there are column names on your pwm matrix, and that currently causes the colSums to not equal a plain vector of 1's without names.  As a temporary fix, if you remove the column names then the function should work. I tested adding column names to the profile matrix and was able to reproduce the bug.  You could remove them via `colnames(TFBSTools::Matrix(cisbp_PWMatrixList[[1]])) <- NULL`

I will fix the function to ignore column names.

**Comment by jkzebrafish** [comment]
Oh ok that's great!  Much easier than what I was thinking, will give it a try.

Thanks so much for your help Alicia!
John

**Comment by AliciaSchep** [comment]
This should now be fixed in latest versions of both motifmatchr and chromVAR. Thanks for bringing up the issue!
